package ubadbtools.recoveryLogAnalyzer.redo.common.logRecords;
import java.util.List;

import java.util.ListIterator;


public class StartCkptLogRecord extends RecoveryLogRecord
{
	private List<String> transactions;
	
	public StartCkptLogRecord(List<String> transactions) 
	{
		this.transactions = transactions;
	}
	
	public List<String> getTransactions()
	{
		return transactions;
	}
	
	public String toString()
	{
		String res;
		ListIterator<String> liter=transactions.listIterator();
		res="<START CKPT (";
		
		if (liter.hasNext()) res=res+liter.next();
		
		while (liter.hasNext())
			res=res+","+liter.next(); 
	
		res=res+")>";
		return res;
	}

	//AUTOGENERATED by Eclipse
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((transactions == null) ? 0 : transactions.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StartCkptLogRecord other = (StartCkptLogRecord) obj;
		if (transactions == null)
		{
			if (other.transactions != null)
				return false;
		}
		else if (!transactions.equals(other.transactions))
			return false;
		return true;
	}
}
