package ubadbtools.recoveryLogAnalyzer.redo.common.recoveryActions;

import java.util.Set;

public class AbortRecoveryAction extends RecoveryAction
{
	private Set<String> transactions;

	public AbortRecoveryAction(Set<String> transactions)
	{
		this.transactions = transactions;
	}
	
	@Override
	public String toString()
	{
		return "- ABORT " + transactions.toString() + " -";
	}

	//AUTOGENERATED by Eclipse
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((transactions == null) ? 0 : transactions.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AbortRecoveryAction other = (AbortRecoveryAction) obj;
		if (transactions == null)
		{
			if (other.transactions != null)
				return false;
		}
		else if (!transactions.equals(other.transactions))
			return false;
		return true;
	}
}
